export const sampleTemples = {
  canvasDimensions: {
    width: 500,
    height: 500,
    background: {
      color: "lightpink",
      uri: "",
    },
  },
  canvasElement: [
    {
      type: "VECTOR",
      xPos: 12,
      yPos: 360,
      height: 90,
      width: 290,
      meta: {
        backgroundColor: "black",
        borderColor: "black",
        borderWidth: 0,
        roundness: 10,
      },
    },
    {
      type: "IMAGE",
      xPos: 180,
      yPos: 80,
      height: 380,
      width: 280,
      meta: {
        roundness: 25,
        backgroundColor: "white",
        uri: "",
        localUri: require("../../assets/images/product1.png"),
      },
    },
    {
      type: "TEXT",
      xPos: 25,
      yPos: 20,
      height: 100,
      width: 100,
      meta: {
        text: "Limited Time",
        fontSize: 22,
        fontWeight: "700",
        fontColor: "black",
      },
    },
    {
      type: "TEXT",
      xPos: 25,
      yPos: 50,
      height: 100,
      width: 100,
      meta: {
        text: "OFFER",
        fontSize: 38,
        fontWeight: "700",
        fontColor: "black",
      },
    },
    {
      type: "TEXT",
      xPos: 25,
      yPos: 330,
      height: 100,
      width: 100,
      meta: {
        text: "Crazy discount",
        fontSize: 18,
        fontWeight: "700",
        fontColor: "black",
      },
    },
    {
      type: "TEXT",
      xPos: 22,
      yPos: 368,
      height: 100,
      width: 100,
      meta: {
        text: "BUY 1 GET 1",
        fontSize: 28,
        fontWeight: "700",
        fontColor: "white",
      },
    },
  ],
};
